{% set name = "questionary" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8681b9d9ec751347ab11af2204d063b856d06845b07b442951e081780e8cb8a6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry >=1.0.5
  run:
    - python >=3.6
    - prompt_toolkit <=3.0.36,>=2.0

test:
  imports:
    - questionary
    - questionary.prompts

about:
  home: https://github.com/tmbo/questionary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library to build pretty command line prompts.
  description: Easy to use multi-select lists, confirmations, free text prompts...
  doc_url: https://github.com/tmbo/questionary#documentation
  dev_url: https://github.com/tmbo/questionary

extra:
  recipe-maintainers:
    - apeltzer
    - ewels
